### ISSUE TITLE
Parse method arguments and more

### ISSUE THREAD

**Issue by thomassjogren** [shershen08/vue-styleguide-generator#10]
Nice work done with this.

As it is already parsing the methods, it would be nice to extend it to parse additional information like method arguments and emitted events.

Going to try run this on a project at work to see how it comes out.

**Comment by shershen08** [comment]
Thanks for the note @thomassjogren. 
Events could be an option, true;
 however I didn't quite get your point about parsing method arguments. 

Let me know how your experience with running the generator on your project was!

**Comment by shershen08** [comment]
closing since no details provided (https://github.com/shershen08/vue-styleguide-generator#questions--bugs)
feel free to contribute and create PR if you have some implementation!
