### ISSUE TITLE
No components demo?

### ISSUE THREAD

**Issue by muhajirdev** [shershen08/vue-styleguide-generator#11]
Hi, really nice projects, and i appreciate it.

One question, when i saw demo from the link on README.
There is no demo of the UI, well there are documentation, and props and etc. But there is no demo of the UI components itself. Is it intended to be like this or the development is not there yet or there is a bug?

Thanks

**Comment by shershen08** [comment]
Unfortunately this feature it's not yet implemented @muhajirframe, see in 'contributions wellcome' section of the README

**Comment by shershen08** [comment]
So closing, since answered

**Comment by rafaesc** [comment]
Hello @muhajirframe 
I have developed what you need
https://github.com/vue-styleguidist/vue-styleguidist
