### ISSUE TITLE
Generator doesn't look for files in included in a .vue file.

### ISSUE THREAD

**Issue by StefanJanssen95** [shershen08/vue-styleguide-generator#2]
My vue files look like:
```
/// dev-test.vue
<template src="./dev-test.html"></template>
<script src="./dev-test.js" lang="js"></script>
<style src="./dev-test.scss" lang="scss"></style>
```
I prefer to seperate the component files in one folder. I would like that these components will also be compiled. I tried finding the file which reads the .vue files but I couldn't find it. Could you point this out to me or edit this?

**Comment by shershen08** [comment]
Hello @StefanJanssen95 
Thank you for valid point. I know about this problem, will update the code coming days

**Comment by shershen08** [comment]
now it's working implementation on `dev` branch; I'll merge into master within a day

**Comment by StefanJanssen95** [comment]
It still doesn't seem to work, can that be because it's only checking the referenced .js files (according to your commit message at least) and not the HTML+SCSS?

EDIT:
Im trying to dive into the code as well so I can be of more assistence.

**Comment by shershen08** [comment]
That's correct it's about JS files only yet. What's d u propose for styles/html?

**Comment by StefanJanssen95** [comment]
Nevermind, just checked the demo in the readme again and something in me thought that there was a little example of how the component looks in there as well, but there isn't.

Im currently checking why the dev branch doesn't work with my code. Will update as soon as I know more.

**Comment by shershen08** [comment]
Yes I know what you mean but that involves ssr which I don't know yet how to implement

**Comment by shershen08** [comment]
"dev branch doesn't work with my code. " be aware not to waste too much of our time, yesterday I was doing some refactoring, didn't test that properly yet

**Comment by StefanJanssen95** [comment]
I thought this new implementation was missing some functionalities that were working with the 'normal' vue files, this is not the case so just ignore my messages.

---
The only problem is that my dev-test component doesn't seem to work.
```
/// dev-test.vue
<template src="./dev-test.html"></template>
<script src="./dev-test.js" lang="js"></script>
<style src="./dev-test.scss" lang="scss"></style>
```
```es6
/// dev-test.js
import {API} from '../../constants';

export default {
	name: 'od-dev-test',
	data() {
		return {
		}
	},
	methods: {
		callTestApi(){
			this.$http.get(API.USER).then(response => {
				console.log(response);
			});
		}
	}
};
```
Do you know why it only generates an empty index.html?
I get the following result if I create a ``console.log(console.log(JSON.stringify(nonEmpty));`` on line 31 of generator.js
```json
[
  {
    "dirPath": "src\\components\\logout",
    "files": [
      "src\\components\\logout\\logout.vue"
    ]
  },
  {
    "dirPath": "src\\components\\dev-test",
    "files": [
      "src\\components\\dev-test\\dev-test.md",
      "src\\components\\dev-test\\dev-test.vue"
    ]
  }
]
```

**Comment by StefanJanssen95** [comment]
ah, okay, I thought that it was done because of 

> now it's working implementation on dev branch; I'll merge into master within a day

but I will wait patiently then and try figuring out how the code works so I can learn some new things.

**Comment by shershen08** [comment]
Yes, any improvements in PRs are welcomed!
