### ISSUE TITLE
Preview file is empty

### ISSUE THREAD

**Issue by sibliss** [shershen08/vue-styleguide-generator#9]
Hello there, I'm trying to use vue-styleguide-generator, in the root of my project I have the folder /src/components that contains all my vue components. From the root directory I execute the script:

    `node ./node_modules/vue-styleguide-generator/ --src ./src --dest preview`

But the preview folder remains empty. I tried also with:
    `./src/components`  -> preview empty
     `./`                             -> script does not terminate

What am I doing wrong?

EDIT: typo

**Comment by shershen08** [comment]
Thanks for details, @hawkleaf 
what library you're trying to run it with?
also d u see any errors in terminal ?

**Comment by shershen08** [comment]
Any news in that one @hawkleaf?

**Comment by shershen08** [comment]
Closing, since no answer. Feel free to re-open

**Comment by hawkleaf** [comment]
My apologies, There were no errors in the terminal. This is the result of opening the generated file. https://puu.sh/vLxmg/f94a16ef30.png As you can see it does pick up on my own component, postIndex.vue and error404.vue .

I'm trying to generate some information about the quasar framework. Hence the reason I'm specifically targeting the folder.

If you need anything else feel free to ask, I'll try to respond sooner this time.

**Comment by shershen08** [comment]
Thanks for details @hawkleaf  I'll check how that runs for the `quasar` and get back to you

**Comment by shershen08** [comment]
I've checked it with clean install of **quasar** and it worked fine for me gust generating list of 86 components. I don't know what;s in your **postIndex.vue** component of course. If you could maybe share its code here?

**Comment by hawkleaf** [comment]
@shershen08 I'm afraid there's nothing of use in the component. I just emptied it out and re-ran a bunch of the commands (specifying src etc,) but to no avail.

**Comment by shershen08** [comment]
id I get you right - installing VSG into folder with quasar framework and running it - you see only 2 components (https://puu.sh/vLxmg/f94a16ef30.png ) that you wrote yourself? 
What node/npm version do you use ?

**Comment by hawkleaf** [comment]
I was on 4.2.0. I just updated NPM to 4.6.1 with the same results. I have uploaded my project for you to check out.

https://puu.sh/vTUZm/e04a2a80e7.zip

**Comment by shershen08** [comment]
great, I'll try to run it locally and get back to you.

**Comment by shershen08** [comment]
sorry could you create a zip without **node_modules** folder ?  it can be installed locally out of package.json file.

**Comment by shershen08** [comment]
But wait! 
Do you run it like exactly like this - `npm run build-components --src node_modules/quasar-framework/src/vue-components --all` or its a typo? 
Because you should do either `npm run build-components` OR `node ./node_modules/vue-styleguide-generator/ -src node_modules/quasar-framework/src/vue-components --all` mixing up both does not make sense.

**Comment by hawkleaf** [comment]
Okay seems like this was the problem for me. Nice catch, thanks!

**Comment by shershen08** [comment]
OK, great that we've sinally figured it out.
